package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.PractitionerGroupExample;
import org.opensrp.domain.postgres.PractitionerGroupKey;

public interface PractitionerGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_group
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    long countByExample(PractitionerGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_group
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    int deleteByExample(PractitionerGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_group
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    int deleteByPrimaryKey(PractitionerGroupKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_group
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    int insert(PractitionerGroupKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_group
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    int insertSelective(PractitionerGroupKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_group
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    List<PractitionerGroupKey> selectByExample(PractitionerGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_group
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    int updateByExampleSelective(@Param("record") PractitionerGroupKey record, @Param("example") PractitionerGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_group
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    int updateByExample(@Param("record") PractitionerGroupKey record, @Param("example") PractitionerGroupExample example);
}