package org.opensrp.domain.postgres;

import java.util.Date;

public class PractitionerDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.created_date
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.email
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.enabled
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.first_name
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.gender
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.identifier
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.last_name
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.mobile
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.modified_date
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Date modifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.username
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.uuid
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.creator
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.parent_user_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Integer parentUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.enable_sim_print
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Boolean enableSimPrint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.ss_no
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private String ssNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.app_version
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private String appVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.is_resync
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private String isResync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_details.on_maternity_leave
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Boolean onMaternityLeave;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.id
     *
     * @return the value of team.practitioner_details.id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.id
     *
     * @param id the value for team.practitioner_details.id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.created_date
     *
     * @return the value of team.practitioner_details.created_date
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.created_date
     *
     * @param createdDate the value for team.practitioner_details.created_date
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.email
     *
     * @return the value of team.practitioner_details.email
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.email
     *
     * @param email the value for team.practitioner_details.email
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.enabled
     *
     * @return the value of team.practitioner_details.enabled
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.enabled
     *
     * @param enabled the value for team.practitioner_details.enabled
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.first_name
     *
     * @return the value of team.practitioner_details.first_name
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.first_name
     *
     * @param firstName the value for team.practitioner_details.first_name
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.gender
     *
     * @return the value of team.practitioner_details.gender
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.gender
     *
     * @param gender the value for team.practitioner_details.gender
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.identifier
     *
     * @return the value of team.practitioner_details.identifier
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.identifier
     *
     * @param identifier the value for team.practitioner_details.identifier
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.last_name
     *
     * @return the value of team.practitioner_details.last_name
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.last_name
     *
     * @param lastName the value for team.practitioner_details.last_name
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.mobile
     *
     * @return the value of team.practitioner_details.mobile
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.mobile
     *
     * @param mobile the value for team.practitioner_details.mobile
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.modified_date
     *
     * @return the value of team.practitioner_details.modified_date
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.modified_date
     *
     * @param modifiedDate the value for team.practitioner_details.modified_date
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.username
     *
     * @return the value of team.practitioner_details.username
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.username
     *
     * @param username the value for team.practitioner_details.username
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.uuid
     *
     * @return the value of team.practitioner_details.uuid
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.uuid
     *
     * @param uuid the value for team.practitioner_details.uuid
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.creator
     *
     * @return the value of team.practitioner_details.creator
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.creator
     *
     * @param creator the value for team.practitioner_details.creator
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.parent_user_id
     *
     * @return the value of team.practitioner_details.parent_user_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Integer getParentUserId() {
        return parentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.parent_user_id
     *
     * @param parentUserId the value for team.practitioner_details.parent_user_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setParentUserId(Integer parentUserId) {
        this.parentUserId = parentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.enable_sim_print
     *
     * @return the value of team.practitioner_details.enable_sim_print
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Boolean getEnableSimPrint() {
        return enableSimPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.enable_sim_print
     *
     * @param enableSimPrint the value for team.practitioner_details.enable_sim_print
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setEnableSimPrint(Boolean enableSimPrint) {
        this.enableSimPrint = enableSimPrint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.ss_no
     *
     * @return the value of team.practitioner_details.ss_no
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public String getSsNo() {
        return ssNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.ss_no
     *
     * @param ssNo the value for team.practitioner_details.ss_no
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setSsNo(String ssNo) {
        this.ssNo = ssNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.app_version
     *
     * @return the value of team.practitioner_details.app_version
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.app_version
     *
     * @param appVersion the value for team.practitioner_details.app_version
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.is_resync
     *
     * @return the value of team.practitioner_details.is_resync
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public String getIsResync() {
        return isResync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.is_resync
     *
     * @param isResync the value for team.practitioner_details.is_resync
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setIsResync(String isResync) {
        this.isResync = isResync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_details.on_maternity_leave
     *
     * @return the value of team.practitioner_details.on_maternity_leave
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Boolean getOnMaternityLeave() {
        return onMaternityLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_details.on_maternity_leave
     *
     * @param onMaternityLeave the value for team.practitioner_details.on_maternity_leave
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setOnMaternityLeave(Boolean onMaternityLeave) {
        this.onMaternityLeave = onMaternityLeave;
    }
}