package org.opensrp.domain.postgres;

public class PractitionerGroupKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_group.practitioner_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Integer practitionerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_group.practitioner_group_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Integer practitionerGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_group.practitioner_id
     *
     * @return the value of team.practitioner_group.practitioner_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Integer getPractitionerId() {
        return practitionerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_group.practitioner_id
     *
     * @param practitionerId the value for team.practitioner_group.practitioner_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setPractitionerId(Integer practitionerId) {
        this.practitionerId = practitionerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_group.practitioner_group_id
     *
     * @return the value of team.practitioner_group.practitioner_group_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Integer getPractitionerGroupId() {
        return practitionerGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_group.practitioner_group_id
     *
     * @param practitionerGroupId the value for team.practitioner_group.practitioner_group_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setPractitionerGroupId(Integer practitionerGroupId) {
        this.practitionerGroupId = practitionerGroupId;
    }
}