package org.opensrp.domain.postgres;

import java.util.Date;

public class PractitionerCatchmentArea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_catchment_area.id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_catchment_area.created_date
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_catchment_area.location_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_catchment_area.parent_location_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Integer parentLocationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_catchment_area.modified_date
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Date modifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner_catchment_area.user_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_catchment_area.id
     *
     * @return the value of team.practitioner_catchment_area.id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_catchment_area.id
     *
     * @param id the value for team.practitioner_catchment_area.id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_catchment_area.created_date
     *
     * @return the value of team.practitioner_catchment_area.created_date
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_catchment_area.created_date
     *
     * @param createdDate the value for team.practitioner_catchment_area.created_date
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_catchment_area.location_id
     *
     * @return the value of team.practitioner_catchment_area.location_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_catchment_area.location_id
     *
     * @param locationId the value for team.practitioner_catchment_area.location_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_catchment_area.parent_location_id
     *
     * @return the value of team.practitioner_catchment_area.parent_location_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Integer getParentLocationId() {
        return parentLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_catchment_area.parent_location_id
     *
     * @param parentLocationId the value for team.practitioner_catchment_area.parent_location_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setParentLocationId(Integer parentLocationId) {
        this.parentLocationId = parentLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_catchment_area.modified_date
     *
     * @return the value of team.practitioner_catchment_area.modified_date
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_catchment_area.modified_date
     *
     * @param modifiedDate the value for team.practitioner_catchment_area.modified_date
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner_catchment_area.user_id
     *
     * @return the value of team.practitioner_catchment_area.user_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner_catchment_area.user_id
     *
     * @param userId the value for team.practitioner_catchment_area.user_id
     *
     * @mbg.generated Thu Mar 25 11:29:40 BDT 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}